env:
  global:
    - CC_TEST_REPORTER_ID=045e6c8f64f873901bacc868224b418d9fc72dd73c40feb1af50faf3e96de15d
    - MYSQL_DATABASE=root@(127.0.0.1:3306)/rel_test
    - POSTGRESQL_DATABASE=postgres://postgres@localhost/rel_test

language: go

matrix:
  include:
    - go: "1.10.x"
    - go: "1.11.x"
    - go: "1.12.x"
    - go: "1.13.x"
    - go: "1.14.x"
      env: COVER=-coverprofile=c.out

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE rel_test;'
  - psql -c 'create database rel_test;' -U postgres

install:
  - go get -u github.com/golang/dep/cmd/dep

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - dep ensure
  - go test -race $COVER ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
